-- Create CUSTOMER table
CREATE TABLE IF NOT EXISTS PUBLIC.CUSTOMER (
    CUSTOMER_ID INTEGER NOT NULL DEFAULT -99999,
    CUSTOMER_COUNTRY VARCHAR,
    CUSTOMER_AGE INTEGER,
    CUSTOMER_GENDER VARCHAR,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID)
);

-- Create EXCHANGE_RATE table
CREATE TABLE IF NOT EXISTS PUBLIC.EXCHANGE_RATE (
    EXCHANGE_RATE_ID INTEGER NOT NULL,
    FROM_CURRENCY VARCHAR,
    TO_CURRENCY VARCHAR,
    EFFECTIVE_DATE DATE,
    RATE DECIMAL,
    CONSTRAINT EXCHANGE_RATE_PK PRIMARY KEY (EXCHANGE_RATE_ID)
);

-- Create TRANSACTION table
CREATE TABLE IF NOT EXISTS PUBLIC.TRANSACTION_DETAIL (
    TRANSACTION_DETAIL_ID INTEGER NOT NULL,
    CUSTOMER_ID INTEGER,
    TRANSACTION_TYPE VARCHAR,
    TRANSACTION_AMOUNT DECIMAL,
    TRANSACTION_CURRENCY VARCHAR,
    TRANSACTION_DATE DATE,
    CONSTRAINT TRANSACTION_DETAIL_PK PRIMARY KEY (TRANSACTION_DETAIL_ID),
    CONSTRAINT TRANSACTION_DETAIL_CUSTOMER_FK FOREIGN KEY (
        CUSTOMER_ID
    ) REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE SET DEFAULT
);
